name: Update Docker Hub description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/update-docker-description.yml

jobs:
  update-dockerhub-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: lucasg04/node-ng-test
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true
